### ISSUE TITLE
Q: Proper init value for microsteps()

### ISSUE THREAD

**Issue by thinkyhead** [teemuatlut/Marlin#8]
In the Travis CI test for Marlin, apparently the `float` values `DEFAULT_STEPS_PER_MM` are being used to initialize `stepper.microsteps()`, but they are being converted to `uint16_t` first. The compiler throws a warning about the loss of precision.

https://travis-ci.org/MarlinFirmware/Marlin/builds/258447368#L959-L993

```
In file included from sketch/MarlinConfig.h:30:0,
                 from sketch/stepper_indirection.h:47,
                 from sketch/stepper_indirection.cpp:34:
sketch/stepper_indirection.cpp: In function 'void tmc2130_init()':
sketch/Configuration.h:521:72: warning: narrowing conversion of '1.03690002e+2' from 'double' to 'const uint16_t {aka const unsigned int}' inside { } [-Wnarrowing]
 #define DEFAULT_AXIS_STEPS_PER_UNIT   { 103.69, 106.65, 200/1.25, 1000 }  // default steps per unit for SCARA
                                                                        ^
sketch/stepper_indirection.cpp:202:41: note: in expansion of macro 'DEFAULT_AXIS_STEPS_PER_UNIT'
     constexpr uint16_t steps_per_mm[] = DEFAULT_AXIS_STEPS_PER_UNIT;
                                         ^
sketch/Configuration.h:521:72: warning: narrowing conversion of '1.06650002e+2' from 'double' to 'const uint16_t {aka const unsigned int}' inside { } [-Wnarrowing]
 #define DEFAULT_AXIS_STEPS_PER_UNIT   { 103.69, 106.65, 200/1.25, 1000 }  // default steps per unit for SCARA
                                                                        ^
sketch/stepper_indirection.cpp:202:41: note: in expansion of macro 'DEFAULT_AXIS_STEPS_PER_UNIT'
     constexpr uint16_t steps_per_mm[] = DEFAULT_AXIS_STEPS_PER_UNIT;
                                         ^
sketch/Configuration.h:521:72: warning: narrowing conversion of '1.6e+2' from 'double' to 'const uint16_t {aka const unsigned int}' inside { } [-Wnarrowing]
 #define DEFAULT_AXIS_STEPS_PER_UNIT   { 103.69, 106.65, 200/1.25, 1000 }  // default steps per unit for SCARA
                                                                        ^
sketch/stepper_indirection.cpp:202:41: note: in expansion of macro 'DEFAULT_AXIS_STEPS_PER_UNIT'
     constexpr uint16_t steps_per_mm[] = DEFAULT_AXIS_STEPS_PER_UNIT;
```

These values don't seem the proper ones to use for initializing `stepper.microsteps()`. Should we be using something else? Or, should `microsteps` be taking `float`? As I understand it, there's very rarely an exact integer number of microsteps per mm.

**Comment by teemuatlut** [comment]
microsteps() and DEFAULT_AXIS_STEPS_PER_UNIT don't really have much to do with each other and one is not used to initiate another.

The default steps per mm are used for calculating the stealthChop -> spreadCycle transition velocity (we need the clock time between individual microsteps). The stepper microsteps are defined in configuration_adv.
The steppers don't need to know how many steps it takes for a mm and I don't think there are any floats used in the stepper registry.
> As I understand it, there's very rarely an exact integer number of microsteps per mm.

I'd actually say the opposite. Forever the values for a typical cartesian has been 80, 80, 4000, ~500. The reason we're seeing the float values here is because of the SCARA configuration. This would also be the reason why I haven't seen the warning for myself.

> Should we be using something else?

No, the logic behind should be sound, but we maybe should use values from the planner instead of the default ones. This would account for user changing the values with a command.

> Or, should microsteps be taking float?

The values are very clearly defined as 0, 2, 4, 8, 16, 32, 64, 128, 256.

Would you like a quick PR to clear the warnings?
